#!/usr/bin/env bash
# [fork-only] Build the iOS app for the self-hosted backend.
#
# Sign-in: the app's Firebase Auth SDK runs in emulator mode, so its sign-in
# calls go to the backend's Casdoor stand-in (routers/casdoor_auth.py) instead
# of Google. The SDK speaks only plain http in that mode, so they go to the
# backend's tailnet http address (chart value tailscaleHttp, e.g.
# omi-auth.<tailnet>.ts.net). All other traffic uses the https API URL.
#
# Firebase gets placeholder settings (project omi-selfhosted), so nothing is
# sent to Google: no crash reports, no analytics, no push.
#
# Usage (from anywhere):
#   app/scripts/selfhosted-ios.sh run [-d <device-id>]  # install a release build on a connected iPhone
#   app/scripts/selfhosted-ios.sh ipa      # build an .ipa for TestFlight
#   app/scripts/selfhosted-ios.sh upload   # build and upload to TestFlight
#
# Settings come from app/.env.selfhosted (gitignored):
#   OMI_API_BASE_URL=https://omi.example.ts.net/
#   OMI_AUTH_HTTP_HOST=omi-auth.example.ts.net
#   IOS_BUNDLE_ID=com.example.omi-selfhosted
#   IOS_TEAM_ID=ABCDE12345
#   IOS_DISPLAY_NAME="Omi SH"          # optional
#   FLUTTER=~/fvm/versions/3.44.5/bin/flutter  # optional; upstream CI uses 3.44.5
#   BUILD_NUMBER=2                      # optional; TestFlight needs a new one per upload

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

MODE="${1:-}"
case "$MODE" in run | ipa | upload) ;; *)
  sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
  ;;
esac

[[ -f .env.selfhosted ]] || { echo "Missing $APP_DIR/.env.selfhosted (see the top of this script)." >&2; exit 1; }
set -a
# shellcheck disable=SC1091
source .env.selfhosted
set +a
for var in OMI_API_BASE_URL OMI_AUTH_HTTP_HOST IOS_BUNDLE_ID IOS_TEAM_ID; do
  [[ -n "${!var:-}" ]] || { echo "Set $var in .env.selfhosted" >&2; exit 1; }
done
[[ "$OMI_API_BASE_URL" == */ ]] || OMI_API_BASE_URL="$OMI_API_BASE_URL/"
DISPLAY_NAME="${IOS_DISPLAY_NAME:-Omi SH}"
read -r -a FLUTTER_CMD <<<"${FLUTTER:-flutter}"
DART_CMD=("${FLUTTER_CMD[@]}")
DART_CMD[${#DART_CMD[@]}-1]="${DART_CMD[${#DART_CMD[@]}-1]%flutter}dart"
CALLBACK_SCHEME="omi-selfhosted" # must match AppEnvironmentProfile.selfHosted
GEN_DIR="ios/build/selfhosted"   # relative to app/; Xcode paths are relative to ios/

# ── Generated, gitignored inputs ──────────────────────────────────────────────

# Keep a copy of files that a normal upstream setup also writes, once.
backup_once() {
  if [[ -f "$1" && ! -f "$1.pre-selfhosted" ]] && ! grep -q "omi-selfhosted" "$1"; then
    cp "$1" "$1.pre-selfhosted"
  fi
}

mkdir -p "$GEN_DIR" ios/Config/Prod ios/Runner

for f in lib/firebase_options_prod.dart ios/Config/Prod/GoogleService-Info.plist .env; do backup_once "$f"; done

sed -e "s/demo-omi-local/omi-selfhosted/g" \
  -e "s/com\.friend-app-with-wearable\.ios12\.development/$IOS_BUNDLE_ID/g" \
  -e "s|^// Local-only Firebase options.*|// Placeholder Firebase options for the self-hosted build (generated by scripts/selfhosted-ios.sh).|" \
  lib/firebase_options_local.dart >lib/firebase_options_prod.dart

cp setup/prebuilt/GoogleService-Info-Local.plist ios/Config/Prod/GoogleService-Info.plist
/usr/libexec/PlistBuddy -c "Set :PROJECT_ID omi-selfhosted" -c "Set :BUNDLE_ID $IOS_BUNDLE_ID" \
  ios/Config/Prod/GoogleService-Info.plist
cp ios/Config/Prod/GoogleService-Info.plist ios/Runner/GoogleService-Info.plist

cat >.env <<EOF
# Generated by scripts/selfhosted-ios.sh for omi-selfhosted; edit .env.selfhosted instead.
API_BASE_URL=$OMI_API_BASE_URL
USE_WEB_AUTH=true
USE_AUTH_CUSTOM_TOKEN=true
EOF
[[ -f .dev.env ]] || cp .env.template .dev.env

# The Runner target pins Runner/Info.plist, so patch it in place for the
# build and restore it on exit: plain http to the sign-in host only, and
# every Firebase collection switched off.
PLIST="ios/Runner/Info.plist"
cp "$PLIST" "$GEN_DIR/Info.plist.orig"
trap 'cp "$GEN_DIR/Info.plist.orig" ios/Runner/Info.plist' EXIT
/usr/libexec/PlistBuddy \
  -c "Add :NSAppTransportSecurity dict" \
  -c "Add :NSAppTransportSecurity:NSExceptionDomains dict" \
  -c "Add :NSAppTransportSecurity:NSExceptionDomains:$OMI_AUTH_HTTP_HOST dict" \
  -c "Add :NSAppTransportSecurity:NSExceptionDomains:$OMI_AUTH_HTTP_HOST:NSExceptionAllowsInsecureHTTPLoads bool true" \
  -c "Add :FirebaseCrashlyticsCollectionEnabled bool false" \
  -c "Add :FirebaseMessagingAutoInitEnabled bool false" \
  -c "Add :FirebaseDataCollectionDefaultEnabled bool false" \
  "$PLIST"
plutil -lint "$PLIST" >/dev/null

# No capabilities: push, HealthKit, Sign in with Apple and the upstream app
# group all need setup on upstream's Apple team. Used by every target.
cat >"$GEN_DIR/empty.entitlements" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict/>
</plist>
EOF

# Command-line build settings: they apply to every target (app, widget, watch).
export FLUTTER_XCODE_APP_BUNDLE_IDENTIFIER="$IOS_BUNDLE_ID"
export FLUTTER_XCODE_DEVELOPMENT_TEAM="$IOS_TEAM_ID"
export FLUTTER_XCODE_CODE_SIGN_STYLE=Automatic
export FLUTTER_XCODE_CODE_SIGN_ENTITLEMENTS="build/selfhosted/empty.entitlements"
export FLUTTER_XCODE_AUTH_CALLBACK_SCHEME="$CALLBACK_SCHEME"
export FLUTTER_XCODE_BUNDLE_DISPLAY_NAME="$DISPLAY_NAME"
# The watch app reads MARKETING_VERSION / CURRENT_PROJECT_VERSION, not the
# Flutter version; App Store Connect rejects an upload when they differ.
VERSION_LINE="$(sed -n 's/^version: *//p' pubspec.yaml)"
export FLUTTER_XCODE_MARKETING_VERSION="${VERSION_LINE%%+*}"
export FLUTTER_XCODE_CURRENT_PROJECT_VERSION="${BUILD_NUMBER:-${VERSION_LINE#*+}}"

DEFINES=(
  --dart-define=OMI_APP_PROFILE=self_hosted
  --dart-define=OMI_API_BASE_URL="$OMI_API_BASE_URL"
  --dart-define=OMI_FIREBASE_AUTH_EMULATOR_HOST="$OMI_AUTH_HTTP_HOST"
  --dart-define=OMI_FIREBASE_AUTH_EMULATOR_PORT=80
)
BUILD_ARGS=(--flavor prod --release "${DEFINES[@]}")
[[ -n "${BUILD_NUMBER:-}" ]] && BUILD_ARGS+=(--build-number="$BUILD_NUMBER")

"${FLUTTER_CMD[@]}" pub get
"${FLUTTER_CMD[@]}" precache --ios
(cd ios && { pod install || pod install --repo-update; })
"${DART_CMD[@]}" run build_runner build

case "$MODE" in
  run)
    "${FLUTTER_CMD[@]}" run "${BUILD_ARGS[@]}" "${@:2}"
    ;;
  ipa | upload)
    EXPORT_PLIST="$GEN_DIR/ExportOptions.plist"
    cat >"$EXPORT_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key><string>app-store-connect</string>
  <key>teamID</key><string>$IOS_TEAM_ID</string>
  <key>signingStyle</key><string>automatic</string>
  <key>destination</key><string>$([[ "$MODE" == upload ]] && echo upload || echo export)</string>
  <key>manageAppVersionAndBuildNumber</key><false/>
</dict>
</plist>
EOF
    "${FLUTTER_CMD[@]}" build ipa "${BUILD_ARGS[@]}" --export-options-plist="$EXPORT_PLIST"
    echo "Done. Output: $APP_DIR/build/ios/ipa/"
    ;;
esac
